import React from "react";
import {
  Document,
  Image,
  Page,
  StyleSheet,
  Text,
  View,
} from "@react-pdf/renderer";

import type { ReportSeriesPoint } from "@/components/marketing/report/performance-line-chart";
import type { KpiStat, ChannelSummary } from "@/lib/marketing/report/client-report-metrics";
import {
  canonicalReportPlatformSlug,
  type CampaignTableRow,
  type YtdMonthTableRow,
} from "@/lib/marketing/report/report-tab-platform";

export type ConversionBreakdownPdfRow = {
  id: string;
  label: string;
  conversionType: string;
  current: number;
  prior: number;
};

/** One tab’s worth of content (Overview or a single platform). */
export type ReportPdfSection = {
  slug: string;
  /** e.g. "Overview" / "Google Ads" */
  viewTitle: string;
  hero: KpiStat[];
  conversionRows: ConversionBreakdownPdfRow[];
  channelRows: ChannelSummary[] | null;
  campaignRows: CampaignTableRow[] | null;
  /** Meta tab only — column visibility from client_metric_config. */
  metaCampaignColumnVisibility?: Record<string, boolean>;
  /** Meta ecommerce — Purchases / Purchase Value / ROAS columns. */
  useMetaEcommerceColumns?: boolean;
  /** Rows match the chart dataset (daily Performance Trends series). Split into chunks for pagination. */
  performanceChunks: ReportSeriesPoint[][];
  ytdRows: YtdMonthTableRow[];
};

export type ReportPdfBundle = {
  agencyName: string;
  agencyLogoUrl: string | null;
  agencyPrimaryColor: string;
  clientName: string;
  dateRangeLabel: string;
  generatedAtLabel: string;
  /** Overview first, then each platform tab in product order. */
  sections: ReportPdfSection[];
};

type PdfHeaderProps = {
  agencyLogoUrl: string | null;
  clientName: string;
  viewTitle: string;
  dateRangeLabel: string;
};

export function ReportPdfDocument({ bundle }: { bundle: ReportPdfBundle }) {
  const styles = buildStyles(bundle.agencyPrimaryColor);
  const primary = bundle.agencyPrimaryColor;
  const footer = (
    <View style={styles.footer}>
      <Text style={styles.subtle}>Generated by {bundle.agencyName}</Text>
      <Text style={styles.subtle}>{bundle.generatedAtLabel}</Text>
    </View>
  );

  const sectionCount = bundle.sections.length;

  return (
    <Document>
      {bundle.sections.flatMap((section, sectionIndex) => {
        const dailyChunks = section.performanceChunks ?? [];
        const firstDaily = dailyChunks[0];
        const restDaily = dailyChunks.slice(1);
        const hasPerfTrends = dailyChunks.some((c) => c.length > 0);
        const isLastSection = sectionIndex === sectionCount - 1;
        const headerProps: PdfHeaderProps = {
          agencyLogoUrl: bundle.agencyLogoUrl,
          clientName: bundle.clientName,
          viewTitle: section.viewTitle,
          dateRangeLabel: bundle.dateRangeLabel,
        };

        return [
          <Page key={`${section.slug}-main`} size="LETTER" style={styles.page}>
            <PdfHeader header={headerProps} styles={styles} />
            <HeroSection hero={section.hero} primaryColor={primary} styles={styles} />
            {hasPerfTrends ? (
              <>
                <PdfSectionTitle styles={styles}>Performance Trends</PdfSectionTitle>
                <View style={styles.surfaceCard}>
                  {firstDaily != null && firstDaily.length ? (
                    <PerfTableChunk rows={firstDaily} styles={styles} />
                  ) : (
                    <Text style={styles.muted}>No daily performance rows for this selection.</Text>
                  )}
                </View>
              </>
            ) : null}
            {section.conversionRows.length > 0 ? (
              <>
                <PdfSectionTitle styles={styles}>Conversion Breakdown</PdfSectionTitle>
                <ConversionBreakdownCards
                  rows={section.conversionRows}
                  styles={styles}
                  primaryColor={primary}
                />
              </>
            ) : null}
            {section.channelRows != null && section.channelRows.length > 0 ? (
              <>
                <PdfSectionTitle styles={styles}>Channel Breakdown</PdfSectionTitle>
                <ChannelBreakdownCards rows={section.channelRows} styles={styles} />
              </>
            ) : null}
            {section.campaignRows != null ? (
              <>
                <CampaignSectionTitle styles={styles}>Campaign performance</CampaignSectionTitle>
                <CampaignTable
                  rows={section.campaignRows}
                  styles={styles}
                  useMetaReachColumns={canonicalReportPlatformSlug(section.slug) === "meta"}
                  useEcommerceColumns={section.useMetaEcommerceColumns === true}
                  columnVisibility={
                    section.useMetaEcommerceColumns ? undefined : section.metaCampaignColumnVisibility
                  }
                />
              </>
            ) : null}
          </Page>,
          ...(hasPerfTrends
            ? restDaily.map((chunk, idx) => (
                <Page key={`${section.slug}-daily-${idx}`} size="LETTER" style={styles.page}>
                  <PdfHeader header={headerProps} styles={styles} minimal />
                  <Text style={[styles.subtle, { marginBottom: 10 }]}>{bundle.dateRangeLabel}</Text>
                  <Text style={[styles.sectionTitleCenter, { marginTop: 0, marginBottom: 8 }]}>
                    Performance Trends (continued)
                  </Text>
                  <View style={styles.surfaceCard}>
                    <PerfTableChunk rows={chunk} styles={styles} />
                  </View>
                </Page>
              ))
            : []),
          <Page key={`${section.slug}-ytd`} size="LETTER" style={styles.page}>
            <PdfHeader header={headerProps} styles={styles} minimal />
            <Text style={[styles.subtle, { marginBottom: 10 }]}>{bundle.dateRangeLabel}</Text>
            <PdfSectionTitle styles={styles}>Year to Date</PdfSectionTitle>
            <View style={styles.surfaceCard}>
              <YtdTable
                rows={section.ytdRows}
                styles={styles}
                useEcommerceColumns={section.useMetaEcommerceColumns === true}
              />
            </View>
            {isLastSection ? footer : null}
          </Page>,
        ];
      })}
    </Document>
  );
}

function PdfHeader({
  header,
  styles,
  minimal,
}: {
  header: PdfHeaderProps;
  styles: ReturnType<typeof buildStyles>;
  /** Continuation pages: compact strip so each tab’s pages stay visually tied to the same section. */
  minimal?: boolean;
}) {
  if (minimal) {
    return (
      <View style={styles.headerMinimal}>
        <Text style={styles.viewTag}>{header.viewTitle}</Text>
        <Text style={styles.subtle}>{header.clientName}</Text>
      </View>
    );
  }
  return (
    <View style={styles.header}>
      {header.agencyLogoUrl ? (
        // @react-pdf/renderer's Image is not a DOM img — no alt prop in ImageProps (PDF output).
        // eslint-disable-next-line jsx-a11y/alt-text -- decorative agency mark in PDF header
        <Image src={header.agencyLogoUrl} style={styles.logo} />
      ) : (
        <View />
      )}
      <View style={styles.headerRight}>
        <Text style={styles.viewTag}>{header.viewTitle}</Text>
        <Text style={styles.clientName}>{header.clientName}</Text>
        <Text style={styles.subtle}>{header.dateRangeLabel}</Text>
      </View>
    </View>
  );
}

function formatKpiPdf(k: KpiStat, value: number): string {
  if (k.format === "currency") return formatCurrency(value);
  if (k.format === "percent") return `${value.toFixed(1)}%`;
  if (k.format === "multiplier") return `${value.toFixed(2)}x`;
  return formatWhole(value);
}

function HeroSection({
  hero,
  primaryColor,
  styles,
}: {
  hero: KpiStat[];
  primaryColor: string;
  styles: ReturnType<typeof buildStyles>;
}) {
  return (
    <View style={styles.kpiRow}>
      {hero.map((k) => {
        const deltaPct = k.prior > 0 ? ((k.current - k.prior) / k.prior) * 100 : 0;
        const favorable = k.lowerIsBetter ? deltaPct <= 0 : deltaPct >= 0;
        const arrow = deltaPct >= 0 ? "\u25B2" : "\u25BC";
        return (
          <View key={k.label} style={[styles.kpiCard, { borderTopColor: primaryColor }]}>
            <Text style={styles.kpiLabel}>{k.label}</Text>
            <Text style={styles.kpiValue}>{formatKpiPdf(k, k.current)}</Text>
            <Text style={styles.kpiPrior}>
              Prior:&nbsp;
              {formatKpiPdf(k, k.prior)}
            </Text>
            <Text style={favorable ? styles.kpiDeltaUp : styles.kpiDeltaDown}>
              {arrow + " "} {Math.abs(deltaPct).toFixed(1)}%
            </Text>
          </View>
        );
      })}
    </View>
  );
}

function PdfSectionTitle({
  children,
  styles,
}: {
  children: string;
  styles: ReturnType<typeof buildStyles>;
}) {
  return <Text style={styles.sectionTitleCenter}>{children}</Text>;
}

/** Left-aligned subtitle like dashboard campaign section (vs centered section headings). */
function CampaignSectionTitle({
  children,
  styles,
}: {
  children: string;
  styles: ReturnType<typeof buildStyles>;
}) {
  return <Text style={styles.campaignSectionTitle}>{children}</Text>;
}

function ConversionBreakdownCards({
  rows,
  styles,
  primaryColor,
}: {
  rows: ConversionBreakdownPdfRow[];
  styles: ReturnType<typeof buildStyles>;
  primaryColor: string;
}) {
  if (!rows?.length) return null;
  return (
    <View style={styles.cardGridFour}>
      {rows.map((r) => (
        <ConversionBreakdownPdfCard key={r.id} item={r} styles={styles} primaryColor={primaryColor} />
      ))}
    </View>
  );
}

function ConversionBreakdownPdfCard({
  item,
  styles,
  primaryColor,
}: {
  item: ConversionBreakdownPdfRow;
  styles: ReturnType<typeof buildStyles>;
  primaryColor: string;
}) {
  const badge = conversionTypeBadgePdf(item.conversionType);
  const delta = deltaTone(item.current, item.prior, styles);
  return (
    <View style={[styles.convCard, { borderTopColor: primaryColor }]}>
      <Text style={styles.convCardLabel}>{item.label}</Text>
      <View style={[styles.typeBadge, { backgroundColor: badge.bg }]}>
        <Text style={styles.typeBadgeText}>{badge.short}</Text>
      </View>
      <Text style={styles.convCardValue}>{formatWhole(Math.round(item.current))}</Text>
      <Text style={styles.convCardPrior}>
        Prior: {formatWhole(Math.round(item.prior))}
      </Text>
      <Text style={delta.style}>
        {delta.arrow}
        {delta.pctText}
      </Text>
    </View>
  );
}

function ChannelBreakdownCards({
  rows,
  styles,
}: {
  rows: ChannelSummary[];
  styles: ReturnType<typeof buildStyles>;
}) {
  return (
    <View style={styles.cardGridThree}>
      {rows.map((ch) => (
        <View key={ch.name} style={styles.channelCard}>
          <Text style={styles.channelCardTitle}>{ch.name.toUpperCase()}</Text>
          <View style={styles.channelMetricRow}>
            <Text style={styles.channelMetricLabel}>Spend</Text>
            <Text style={styles.channelMetricValue}>{formatCurrency(ch.spend)}</Text>
          </View>
          <View style={styles.channelMetricRow}>
            <Text style={styles.channelMetricLabel}>Conversions</Text>
            <Text style={styles.channelMetricValue}>{formatWhole(ch.conversions)}</Text>
          </View>
          <View style={styles.channelMetricRow}>
            <Text style={styles.channelMetricLabel}>Cost per Conversion</Text>
            <Text style={styles.channelMetricValue}>
              {formatCurrency(ch.spend / Math.max(ch.conversions, 1))}
            </Text>
          </View>
        </View>
      ))}
    </View>
  );
}

function CampaignTable({
  rows,
  styles,
  useMetaReachColumns,
  useEcommerceColumns = false,
  columnVisibility,
}: {
  rows: CampaignTableRow[];
  styles: ReturnType<typeof buildStyles>;
  useMetaReachColumns: boolean;
  useEcommerceColumns?: boolean;
  columnVisibility?: Record<string, boolean>;
}) {
  const metaEcommerce = Boolean(useMetaReachColumns && useEcommerceColumns);
  const metaConfigurable = Boolean(useMetaReachColumns && columnVisibility && !metaEcommerce);

  if (metaEcommerce) {
    type ColDef = { key: string; label: string; value: (r: CampaignTableRow) => string };
    const cols: ColDef[] = [
      { key: "name", label: "Campaign", value: (r) => r.name.slice(0, 80) },
      { key: "impressions", label: "Impr.", value: (r) => formatWhole(Math.round(r.impressions)) },
      { key: "reach", label: "Reach", value: (r) => formatWhole(Math.round(r.reach ?? 0)) },
      { key: "lpv", label: "LPV", value: (r) => formatWhole(Math.round(r.landingPageViews ?? 0)) },
      { key: "spend", label: "Spend", value: (r) => formatCurrency(r.cost) },
      { key: "purchases", label: "Purchases", value: (r) => formatWhole(Math.round(r.purchases ?? 0)) },
      {
        key: "purchase_value",
        label: "Purchase Value",
        value: (r) => formatCurrency(r.purchaseValue ?? 0),
      },
      {
        key: "roas",
        label: "ROAS",
        value: (r) =>
          r.cost > 0 && (r.roas ?? 0) > 0 ? `${(r.roas ?? 0).toFixed(1)}x` : "—",
      },
    ];
    const nameWidth = 22;
    const metricWidth = (100 - nameWidth) / (cols.length - 1);
    const widths = cols.map((_, i) => (i === 0 ? nameWidth : metricWidth));
    return (
      <>
        <TableHeader cols={cols.map((c) => c.label)} widths={widths} styles={styles} />
        {(rows ?? []).length === 0 ? (
          <Text style={styles.muted}>No campaign breakdown.</Text>
        ) : (
          rows.map((r) => (
            <TableRow
              key={r.id}
              cols={cols.map((c) => c.value(r))}
              widths={widths}
              styles={styles}
            />
          ))
        )}
      </>
    );
  }

  if (metaConfigurable) {
    type ColDef = { key: string; label: string; value: (r: CampaignTableRow) => string };
    const cols: ColDef[] = [{ key: "name", label: "Campaign", value: (r) => r.name.slice(0, 80) }];
    const push = (shown: boolean, key: string, label: string, value: (r: CampaignTableRow) => string) => {
      if (shown) cols.push({ key, label, value });
    };
    const shown = (key: string) => columnVisibility![key] !== false;
    const optIn = (key: string) => columnVisibility![key] === true;

    push(shown("impressions"), "impressions", "Impr.", (r) => formatWhole(Math.round(r.impressions)));
    push(shown("reach"), "reach", "Reach", (r) => formatWhole(Math.round(r.reach ?? 0)));
    push(shown("landing_page_views"), "landing_page_views", "LPV", (r) =>
      formatWhole(Math.round(r.landingPageViews ?? 0)),
    );
    push(shown("clicks"), "clicks", "Clicks", (r) => formatWhole(Math.round(r.clicks)));
    push(shown("avgCpc"), "avgCpc", "CPC", (r) =>
      r.clicks > 0 ? formatCurrency(r.cost / r.clicks) : "—",
    );
    push(shown("spend"), "spend", "Cost", (r) => formatCurrency(r.cost));
    push(shown("conversions"), "conversions", "Conv.", (r) => formatWhole(Math.round(r.conversions)));
    push(shown("cpl"), "cpl", "Cost / conv.", (r) =>
      r.conversions > 0 ? formatCurrency(r.cost / r.conversions) : "—",
    );
    push(optIn("contact_forms"), "contact_forms", "Contact Forms", (r) =>
      formatWhole(Math.round(r.contactForms ?? 0)),
    );
    push(optIn("purchases"), "purchases", "Purchases", (r) => formatWhole(Math.round(r.purchases ?? 0)));
    push(optIn("purchase_value"), "purchase_value", "Purchase Value", (r) =>
      formatCurrency(r.purchaseValue ?? 0),
    );
    push(optIn("roas"), "roas", "ROAS", (r) =>
      r.cost > 0 && (r.roas ?? 0) > 0 ? `${(r.roas ?? 0).toFixed(2)}x` : "—",
    );

    const nameWidth = 28;
    const metricWidth = cols.length > 1 ? (100 - nameWidth) / (cols.length - 1) : 10;
    const widths = cols.map((_, i) => (i === 0 ? nameWidth : metricWidth));

    return (
      <>
        <TableHeader cols={cols.map((c) => c.label)} widths={widths} styles={styles} />
        {(rows ?? []).length === 0 ? (
          <Text style={styles.muted}>No campaign breakdown.</Text>
        ) : (
          rows.map((r) => (
            <TableRow
              key={r.id}
              cols={cols.map((c) => c.value(r))}
              widths={widths}
              styles={styles}
            />
          ))
        )}
      </>
    );
  }

  const headerCols = useMetaReachColumns
    ? ["Campaign", "Impr.", "Reach", "LPV", "Cost", "Conv.", "Cost / conv."]
    : ["Campaign", "Impr.", "Clicks", "CTR", "Cost", "Conv.", "Cost / conv."];
  return (
    <>
      <TableHeader cols={headerCols} widths={[30, 10, 9, 8, 12, 8, 15]} styles={styles} />
      {(rows ?? []).length === 0 ? (
        <Text style={styles.muted}>No campaign breakdown.</Text>
      ) : (
        rows.map((r) => {
          const ctr = formatPct(r.clicks, r.impressions);
          const cpconv = r.conversions > 0 ? formatCurrency(r.cost / r.conversions) : "—";
          const midCols = useMetaReachColumns
            ? [
                formatWhole(Math.round(r.reach ?? 0)),
                formatWhole(Math.round(r.landingPageViews ?? 0)),
              ]
            : [formatWhole(Math.round(r.clicks)), ctr];
          return (
            <TableRow
              key={r.id}
              cols={[
                r.name.slice(0, 80),
                formatWhole(Math.round(r.impressions)),
                ...midCols,
                formatCurrency(r.cost),
                formatWhole(Math.round(r.conversions)),
                cpconv,
              ]}
              widths={[30, 10, 9, 8, 12, 8, 15]}
              styles={styles}
            />
          );
        })
      )}
    </>
  );
}

function PerfTableChunk({
  rows,
  styles,
}: {
  rows: ReportSeriesPoint[];
  styles: ReturnType<typeof buildStyles>;
}) {
  return (
    <>
      <TableHeader
        cols={["Date", "Cost", "Conv.", "CPL", "Impr.", "Clicks", "CPC"]}
        widths={[14, 12, 9, 12, 12, 10, 12]}
        styles={styles}
      />
      {rows.map((r) => (
        <TableRow
          key={r.date}
          cols={[
            formatChartDateLabel(r.date),
            formatCurrency(r.cost),
            formatWhole(Math.round(r.conversions)),
            r.conversions > 0 ? formatCurrency(r.cpl) : "—",
            formatWhole(Math.round(r.impressions)),
            formatWhole(Math.round(r.clicks)),
            r.clicks > 0 ? formatCurrency(r.cpc) : "—",
          ]}
          widths={[14, 12, 9, 12, 12, 10, 12]}
          styles={styles}
        />
      ))}
    </>
  );
}

function YtdTable({
  rows,
  styles,
  useEcommerceColumns = false,
}: {
  rows: YtdMonthTableRow[];
  styles: ReturnType<typeof buildStyles>;
  useEcommerceColumns?: boolean;
}) {
  if (useEcommerceColumns) {
    const widths = [18, 12, 10, 14, 12, 16, 10];
    const headerCols = ["Month", "Impr.", "Clicks", "Spend", "Purchases", "Purch. Value", "ROAS"];
    return (
      <>
        <TableHeader cols={headerCols} widths={widths} styles={styles} />
        {rows.map((r) => (
          <TableRow
            key={r.monthLabel}
            cols={
              r.isFutureMonth
                ? [r.monthLabel, "—", "—", "—", "—", "—", "—"]
                : [
                    r.monthLabel,
                    formatWhole(r.impressions),
                    formatWhole(r.clicks),
                    formatCurrency(r.spend),
                    formatWhole(Math.round(r.purchases ?? 0)),
                    formatCurrency(r.purchaseValue ?? 0),
                    r.spend > 0 && (r.roas ?? 0) > 0 ? `${(r.roas ?? 0).toFixed(1)}x` : "—",
                  ]
            }
            widths={widths}
            styles={styles}
          />
        ))}
      </>
    );
  }

  return (
    <>
      <TableHeader
        cols={["Month", "Impr.", "Clicks", "Spend", "Conv.", "Cost / conv."]}
        widths={[20, 14, 12, 16, 12, 16]}
        styles={styles}
      />
      {rows.map((r) => (
        <TableRow
          key={r.monthLabel}
          cols={
            r.isFutureMonth
              ? [r.monthLabel, "—", "—", "—", "—", "—"]
              : [
                  r.monthLabel,
                  formatWhole(r.impressions),
                  formatWhole(r.clicks),
                  formatCurrency(r.spend),
                  formatWhole(Math.round(r.conversions)),
                  r.conversions > 0 ? formatCurrency(r.costPerConversion) : "—",
                ]
          }
          widths={[20, 14, 12, 16, 12, 16]}
          styles={styles}
        />
      ))}
    </>
  );
}

function TableHeader({
  cols,
  widths,
  styles,
}: {
  cols: string[];
  widths: number[];
  styles: ReturnType<typeof buildStyles>;
}) {
  return (
    <View style={styles.tableHeader}>
      {cols.map((c, i) => (
        <Text key={`h-${i}`} style={[styles.headerCell, { width: `${widths[i]}%` }]}>
          {c}
        </Text>
      ))}
    </View>
  );
}

function TableRow({
  cols,
  widths,
  styles,
}: {
  cols: string[];
  widths: number[];
  styles: ReturnType<typeof buildStyles>;
}) {
  return (
    <View style={styles.tableRow} wrap={false}>
      {cols.map((c, i) => (
        <Text key={`${i}-${String(c)}`} style={[styles.bodyCell, { width: `${widths[i]}%` }]}>
          {c}
        </Text>
      ))}
    </View>
  );
}

function buildStyles(primaryColor: string) {
  return StyleSheet.create({
    page: {
      paddingTop: 26,
      paddingBottom: 22,
      paddingHorizontal: 28,
      fontFamily: "Helvetica",
      fontSize: 9,
      color: "#18181B",
      backgroundColor: "#FFFFFF",
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 14,
      borderBottomWidth: 1,
      borderBottomColor: "#E4E4E7",
      paddingBottom: 8,
    },
    logo: { width: 120, height: 28, objectFit: "contain" },
    headerRight: { alignItems: "flex-end" },
    headerMinimal: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "baseline",
      marginBottom: 8,
      paddingBottom: 6,
      borderBottomWidth: 1,
      borderBottomColor: "#E4E4E7",
    },
    viewTag: { fontSize: 9, fontWeight: 700, color: primaryColor, marginBottom: 2 },
    clientName: { fontSize: 15, fontWeight: 700, color: "#111827" },
    subtle: { color: "#52525B", fontSize: 8.5 },
    muted: { marginTop: 4, marginBottom: 8, fontSize: 8.5, color: "#71717A", fontStyle: "italic" },
    kpiRow: { flexDirection: "row", gap: 7, marginBottom: 14 },
    kpiCard: {
      flex: 1,
      borderWidth: 1,
      borderColor: "#E4E4E7",
      borderTopWidth: 3,
      borderRadius: 8,
      backgroundColor: "#FFFFFF",
      paddingVertical: 10,
      paddingHorizontal: 8,
      textAlign: "center",
    },
    kpiLabel: { color: "#52525B", fontSize: 8.5, marginBottom: 3, fontWeight: 500 },
    kpiValue: { fontSize: 16, fontWeight: 700, color: "#111827", letterSpacing: -0.2 },
    kpiPrior: { marginTop: 4, color: "#71717A", fontSize: 8 },
    kpiDeltaUp: {
      marginTop: 4,
      fontSize: 8.5,
      fontWeight: 600,
      color: "#059669",
      textAlign: "center",
    },
    kpiDeltaDown: {
      marginTop: 4,
      fontSize: 8.5,
      fontWeight: 600,
      color: "#DC2626",
      textAlign: "center",
    },
    surfaceCard: {
      borderWidth: 1,
      borderColor: "#E4E4E7",
      borderTopWidth: 3,
      borderTopColor: primaryColor,
      borderRadius: 8,
      backgroundColor: "#FFFFFF",
      paddingHorizontal: 8,
      paddingVertical: 8,
      marginBottom: 12,
      overflow: "hidden",
    },
    sectionTitleCenter: {
      marginTop: 12,
      marginBottom: 8,
      fontSize: 11,
      fontWeight: 700,
      color: "#111827",
      textAlign: "center",
    },
    cardGridFour: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
      marginBottom: 10,
      justifyContent: "space-between",
    },
    convCard: {
      width: "48%",
      minWidth: "48%",
      borderWidth: 1,
      borderColor: "#E4E4E7",
      borderTopWidth: 3,
      borderRadius: 8,
      backgroundColor: "#FFFFFF",
      paddingVertical: 10,
      paddingHorizontal: 8,
      marginBottom: 4,
      alignItems: "center",
    },
    convCardLabel: {
      fontSize: 8,
      fontWeight: 600,
      color: "#3F3F46",
      textAlign: "center",
      marginBottom: 5,
      lineHeight: 1.25,
    },
    typeBadge: {
      borderRadius: 3,
      paddingVertical: 2,
      paddingHorizontal: 6,
      marginBottom: 6,
    },
    typeBadgeText: {
      fontSize: 7,
      fontWeight: 700,
      color: "#FFFFFF",
      textTransform: "uppercase",
      letterSpacing: 0.4,
    },
    convCardValue: {
      fontSize: 16,
      fontWeight: 700,
      color: "#111827",
      letterSpacing: -0.2,
    },
    convCardPrior: { marginTop: 4, fontSize: 7.5, color: "#A1A1AA" },
    convDeltaNeutral: { marginTop: 5, fontSize: 8.5, fontWeight: 600, color: "#71717A" },
    convDeltaUp: { marginTop: 5, fontSize: 8.5, fontWeight: 600, color: "#059669" },
    convDeltaDown: { marginTop: 5, fontSize: 8.5, fontWeight: 600, color: "#DC2626" },
    cardGridThree: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 7,
      marginBottom: 10,
      justifyContent: "space-between",
    },
    channelCard: {
      width: "31%",
      minWidth: "31%",
      borderWidth: 1,
      borderColor: "#E4E4E7",
      borderRadius: 8,
      backgroundColor: "#FFFFFF",
      paddingVertical: 10,
      paddingHorizontal: 8,
    },
    channelCardTitle: {
      textAlign: "center",
      fontSize: 8,
      fontWeight: 700,
      color: "#71717A",
      letterSpacing: 0.8,
      textTransform: "uppercase",
      marginBottom: 8,
    },
    channelMetricRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 5,
    },
    channelMetricLabel: { fontSize: 8, color: "#71717A" },
    channelMetricValue: { fontSize: 8.5, fontWeight: 700, color: "#111827" },
    campaignSectionTitle: {
      marginTop: 14,
      marginBottom: 6,
      fontSize: 9,
      fontWeight: 600,
      color: "#71717A",
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    tableHeader: {
      flexDirection: "row",
      backgroundColor: "#F4F4F5",
      borderWidth: 1,
      borderColor: "#E4E4E7",
      paddingVertical: 4,
      paddingHorizontal: 5,
    },
    headerCell: { fontWeight: 700, fontSize: 7.5, color: "#3F3F46", paddingRight: 3 },
    tableRow: {
      flexDirection: "row",
      borderLeftWidth: 1,
      borderRightWidth: 1,
      borderBottomWidth: 1,
      borderColor: "#E4E4E7",
      paddingVertical: 3,
      paddingHorizontal: 5,
    },
    bodyCell: { fontSize: 7.5, color: "#18181B", paddingRight: 3 },
    footer: {
      marginTop: 14,
      borderTopWidth: 1,
      borderTopColor: "#E4E4E7",
      paddingTop: 6,
      flexDirection: "row",
      justifyContent: "space-between",
    },
  });
}

function conversionTypeBadgePdf(type: string): { bg: string; short: string } {
  const t = (type ?? "other").toLowerCase();
  if (t === "lead") return { bg: "#2563EB", short: "Lead" };
  if (t === "appointment") return { bg: "#9333EA", short: "Appt" };
  if (t === "call") return { bg: "#16A34A", short: "Call" };
  if (t === "chat") return { bg: "#EA580C", short: "Chat" };
  if (t === "purchase") return { bg: "#0891B2", short: "Buy" };
  return { bg: "#71717A", short: "Other" };
}

function deltaTone(
  current: number,
  prior: number,
  styles: ReturnType<typeof buildStyles>,
): { pctText: string; arrow: string; style: (typeof styles)[keyof typeof styles] } {
  if (prior > 0) {
    const pct = ((current - prior) / prior) * 100;
    const pctText = `${pct >= 0 ? "+" : ""}${pct.toFixed(1)}%`;
    if (Math.abs(pct) < 0.005) {
      return { pctText, arrow: "", style: styles.convDeltaNeutral };
    }
    if (pct > 0) return { pctText, arrow: "\u25B2 ", style: styles.convDeltaUp };
    return { pctText, arrow: "\u25BC ", style: styles.convDeltaDown };
  }
  if (prior === 0 && current > 0) {
    return { pctText: "New", arrow: "\u25B2 ", style: styles.convDeltaUp };
  }
  return { pctText: "0%", arrow: "", style: styles.convDeltaNeutral };
}

function formatPct(num: number, den: number): string {
  if (den <= 0) return "—";
  return `${((num / den) * 100).toFixed(2)}%`;
}

function formatCurrency(value: number): string {
  return value.toLocaleString("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
}

function formatWhole(value: number): string {
  return Math.round(value).toLocaleString("en-US");
}

function formatChartDateLabel(iso: string): string {
  const d = new Date(`${iso}T00:00:00.000Z`);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric", timeZone: "UTC" });
}

export function chunkReportSeriesPoints(rows: ReportSeriesPoint[], maxPerPage: number): ReportSeriesPoint[][] {
  if (rows.length === 0) return [[]];
  const out: ReportSeriesPoint[][] = [];
  for (let i = 0; i < rows.length; i += maxPerPage) {
    out.push(rows.slice(i, i + maxPerPage));
  }
  return out;
}
